Repository pulumi/pulumi-random, pull requests merged in 2019-06, with the labels that each got.

#28 Manage CHANGELOG with chg(1)
  CHANGELOG.md
Labels: enhancement

#29 Update pulumi-terraform to 7ace3e9b5f
  CHANGELOG.md
  go.mod
  go.sum
  sdk/nodejs/provider.ts
  sdk/nodejs/randomId.ts
  sdk/nodejs/randomInteger.ts
  sdk/nodejs/randomPet.ts
  sdk/nodejs/randomShuffle.ts
  sdk/nodejs/randomString.ts
  sdk/nodejs/randomUuid.ts
Labels: area/providers

#30 Update pulumi-terraform to 3635bed3a5
  go.mod
  go.sum
Labels: area/providers

#31 Update .travis.yml to scripts
  .travis.yml
Labels: area/providers, impact/no-changelog-required
